export enum FEATURES {
	USERS = "USERS",
	AUTH = "AUTH",
	COUNTRIES = "COUNTRIES",
	DEPARTMENTS = "DEPARTMENTS",
	CITIES = "CITIES",
	SCHOOLS = "SCHOOLS",
	DISABILITIES = "DISABILITIES",
	EDUCATION_LEVELS = "EDUCATION_LEVELS",
	EDUCATION_MODES = "EDUCATION_MODES",
	ETHNIC_GROUPS = "ETHNIC_GROUPS",
	LANGUAGES = "LANGUAGES",
	SESSIONS = "SESSIONS",
	SPECIALITIES = "SPECIALITIES"
}
