export * from "./disability.entity"
export * from "./education-levels.entity"
export * from "./education-mode.entity"
export * from "./ethnic-group.entity"
export * from "./lenguages.entity"
export * from "./school.entity"
export * from "./session.entity"
export * from "./speciality.entity"
